apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddhtfjh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddhtfjh
  template:
    metadata:
      labels:
        app: ddhtfjh
    spec:
      containers:
      - image: okteto.dev/ddhtfjh:latest
        name: ddhtfjh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8acb70d0-04d4-11ed-b939-0242ac120002"
        - name: Vless_Path
          value: "/vl96dtf4s"
        - name: Vmess_UUID
          value: "8acb70d0-04d4-11ed-b939-0242ac120002"
        - name: Vmess_Path
          value: "/vm123dtt7fy"
        - name: Share_Path
          value: "/v2link"
